### ISSUE TITLE
why i can not find GL/EigenOpenGLSupport3.h

### ISSUE THREAD

**Issue by RenFeiTemp** [OpenGP/OpenGP#22]
does it had been removed?

**Comment by ataiya** [comment]
Yes, you are compiling this, which is not maintained
(Qt has been a pain for modern OpenGL, as they didn't move to GL4 fully)

#--- unstable / obsolete applications
#add_subdirectory(apps/qglviewer)

**Comment by hrwhisper** [comment]
Meet the same problem when I compile Hmodel. Where can I  download the file?
