### ISSUE TITLE
I can`t  configure  openGP by Cmake

### ISSUE THREAD

**Issue by snjxyl** [OpenGP/OpenGP#23]
![xr8571jvvur 2gu p9yq](https://user-images.githubusercontent.com/22437554/28907034-8767de1e-784e-11e7-91d5-aaa4975ac205.png)

I really need openGP.lib(win32 release).

**Comment by snjxyl** [comment]
![image](https://user-images.githubusercontent.com/22437554/28907500-276f5c6e-7851-11e7-98ce-74ff9f4adbb3.png)
i changed Cmake Version missing Files

**Comment by taiya** [comment]
Hi there, this repo was mostly when I was teaching at Victoria, and as the rendering backend of research projects. As I have moved to ML, I am not maintaining it (as you can tell). That said, feel free to send a pull request with changes!
