### ISSUE TITLE
Code improvements results from Cppcheck

### ISSUE THREAD

**Issue by jensdenbraber** [OpenGP/OpenGP#26]
I ran [cppcheck](https://github.com/danmar/cppcheck) on the OpenGP codebase which resulted in the some code improvements. 

Download the results here: 
[OpenGP_cppcheck.zip](https://github.com/OpenGP/OpenGP/files/4451711/OpenGP_cppcheck.zip)

**Comment by ataiya** [comment]
Hi Jens, this repo was mostly when I was teaching at Victoria, and as the rendering backend of research projects. As I have moved to ML, I am not maintaining it (as you can tell).

That said, feel free to send a pull request with changes!
